name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install Node.js dependencies
      - name: Install dependencies
        run: npm ci

      # Start the application (make sure the app is listening on port 3000)
      - name: Start application
        run: npm start &
        env:
          NODE_ENV: test

      # Wait for the app to be ready on port 3000
      - name: Wait for app to be ready
        run: npx wait-on http://localhost:3000 --timeout=180000

      # Run Cypress tests
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          headless: true
          spec: "**/*.cy.js"
          wait-on: "http://localhost:3000"
          wait-on-timeout: 180000

      # Post-test: Shut down the application
      - name: Stop application
        run: kill $(lsof -t -i:3000)
