name: Lint, Build, and Cypress Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run ESLint
      - name: Run ESLint
        run: npx eslint .

  cypress-test:
    name: Build and Run Cypress with Docker-in-Docker
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.16
        options: > 
          --privileged 
          --volume /var/run/docker.sock:/var/run/docker.sock
        ports:
          - 3000:3000
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx (enables Docker Compose)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Set up QEMU for cross-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Build and start application using Docker Compose
      - name: Build and start services
        run: docker-compose up -d --build

      # Run Cypress tests in Docker
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          start: docker-compose up -d
          wait-on: http://localhost:3000
          config-file: cypress.json
          browser: chrome
          headless: true

      # Shut down Docker Compose services
      - name: Shutdown Docker Compose
        run: docker-compose down
