name: Cypress Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-test:
    name: Build and Run Cypress with Docker-in-Docker
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.16
        options: > 
          --privileged 
          --volume /var/run/docker.sock:/var/run/docker.sock
        ports:
          - 3000:3000
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      # Install dependencies with --unsafe-perm to avoid permissions issues
      - name: Install dependencies
        run: npm ci --unsafe-perm

      # Build and start application using Docker Compose
      - name: Build and start services
        run: docker-compose up -d --build

      # Wait for the application to be ready (increase timeout to 180 seconds)
      - name: Wait for app to be ready
        run: npx wait-on http://localhost:3000 --timeout=180000

      # Run Cypress tests in Docker
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          start: docker-compose up -d
          wait-on: http://localhost:3000
          wait-on-timeout: 180000  # Increase the wait-on timeout to 180 seconds
          config-file: cypress.json
          browser: chrome
          headed: false
          spec: "**/*.cy.js"

      # Shut down Docker Compose services
      - name: Shutdown Docker Compose
        run: docker-compose down
