name: Cypress Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:

  cypress-on-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Start application
        run: npm start &
        env:
          NODE_ENV: test

      - name: Wait for app to be ready
        run: npx wait-on http://localhost:3000 --timeout=180000

      - name: Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headless: true
          spec: "**/*.cy.js"

      - name: Stop application
        run: kill $(lsof -t -i:3000)
